id: IEEEFA1F0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:51:21+00:00'
last_modified: '2022-06-07T17:17:13.045882+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ504
  title: དབྱངས་འཆར་བའི་འགྲེལ་པ་ངོ་མཚར་བརྒྱན་གྱི་མེ་ཏོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2784':
      image_group_id: I1CZ683
      title: ''
      total_pages: 822
      order: 1
      base_file: 2784.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
